# Generated by Django 6.0.6 on 2026-06-21 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.8)]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
